version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbt
    ports:
      - "5432:5432"
  minio:
      image: minio/minio:RELEASE.2024-10-13T13-34-11Z
      restart: always
      command: server /data --console-address ":9001"
      volumes:
        - ./data:/data
      environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
        - MINIO_DOMAIN=minio
      ports:
        - "9000:9000"  # MinIO S3 API
        - "9001:9001"  # MinIO Console