version: 2

models:
  - name: fct_registred_by_date
    description: "Количество регистраций за день"
    columns:
      - name: registred_date
        description: "Дата регистрации"
        data_tests:
          - unique
          - not_null
      - name: count
        description: "Количество регистраций"
        data_tests:
          - not_null
